### ISSUE TITLE
Support a wider range of ldflags

### ISSUE THREAD

**Issue by zmackie** [paketo-buildpacks/go-mod-vendor#14]
Its super common in the wild for `-ldflags` to have more than just `-X`, eg `-s -w` and especially `-`-extldflags -static`. Could we support this? Or alternately, provide a config switch that would just add a handful of sane defaults like `clean: true` -> `-ldflags -s -w` and `static: true` -> `-ldflags "-extldflags -static"`

**Comment by ForestEckhardt** [comment]
@zmackie I believe that this addressed by an RFC in the `go-build` buildpack which you can read [here](https://github.com/paketo-buildpacks/go-build/blob/master/rfcs/0002-build-flags.md). I am going to close this issue, if you have any other questions or ideas please feel free to reopen and comment.
