### ISSUE TITLE
Should go-mod-vendor provide a dependency for downstream buildpacks?

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/go-mod-vendor#268]
@brayanhenao and I are exploring creating a Bill Of Materials (BOM) buildpack for golang, similar in principle to: https://github.com/paketo-buildpacks/node-module-bom

This new buildpack would require `go mod`, and could probably benefit from the `vendor` directory being pre-populated during the `build` phase, as it will likely populate that directory if it hasn't already been done.

Both of those two things point to the BOM buildpack having a dependency on this buildpack, but currently I do not believe it is possible to express this relationship because this buildpack does not provide any dependencies for other buildpacks to `detect`.

One of the challenges I'm having with this idea is that I can't think of any meaningful information that this buildpack could provide that the BOM buildpack would actually use. All the BOM buildpack really needs to know is whether the go-mod-vendor buildpack passed its `detect` phase, and it could benefit from the go-mod-vendor buildpack running its `build` phase before it analyses the dependencies and produces a BOM.

I may be misunderstanding the way to represent dependent relationships between buildpacks, though, so please correct me if my understanding is wrong!

**Comment by ForestEckhardt** [comment]
The issue that I think you are running into here is that it is not possible for buildpacks to intercommunicate during detection. I think that there are two clear ways of doing what you are trying to accomplish based on what we do in the rest of the buildpacks ecosystem. 

## Change the build plan
Change the build plan of the the `go-mod-vendor` buildpack to the following:
```toml
[[provides]]
name = "go-modules"

[[requires]]
name = "go"
``` 
This would then allow you to in the `go-module-bom` buildpack to have the following build plan:
```toml
[[requires]]
name = "go"

[[requires]]
name = "go-modules"
```
That would force a direct requirement between `go-module-bom` and `go-mod-vendor`. The only disadvantage to this is that the build plan for `go-build` would also need to be updated to accommodate for non `go mod` apps meaning we would need a build plan that looks similar to the following.
```toml
[[requires]]
name = "go"

[[or]]

[[or.requires]]
name = "go"

[[or.requires]]
name = "go-modules"
```
I think that this API change is unattractive but functional so I could be convinced however this is a lot of changes just to make there be a build plan level relation between `go-mod-vendor` and `go-module-bom`

## Just detect on file existence
I think that the other option that is possible is to detect on similar criteria to that of the `go-mod-vendor` buildpack and then place is later in the buildpack order. This has the distinct advantage of requiring no changes to the existing buildpack build plan APIs however it does mean that there is not a built in link between the app being vendored and the bom generator running. In the case of our metabuildpack we would ensure this behavior by placing the buildpack later in the build order but this has the potential to cause suboptimal if not broken behavior for individuals that decide to build custom buildpack orderings.

## My 2 cents
If I had to chuck some of my own opinion into the mix I think that if you want the initial implementation of the buildpack to happen more quickly I would go with the similar detect logic option. It is the fastest way to get yourself up and running and if a direct buildpack relation becomes necessary it is something that can be implemented  later with a relatively low amount of cost. However, if y'all want to try and make a case for setting up the contract right away that is also reasonable it just might take a little long.

**Comment by arjun024** [comment]
(Not a maintainer) I think the proposed bom-buildpack should be independent enough to be utilized by a user that do not want vendoring, i.e. it should be usable along with just [go-dist](https://github.com/paketo-buildpacks/go-dist) and [go-build](https://github.com/paketo-buildpacks/go-build) buildpacks.
Doesn't the bom-buildpack (or the tool used there) have to generate the bom regardless of if the `vendor` directory is populated? Because even if the app is not vendored, I believe packages will be downloaded into the go-cache dir during compilation which is part of the final image. (Not sure if I have the full picture of the bom-buildpack as my knowledge is only from the post here). So my $0.02 would be against an API as I don't really see a provides-requires relationship here.
